spring.application.name=Notepad App

# mongodb localhost
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

# mongodb atlas
spring.data.mongodb.uri=mongodb+srv://ritik:ritik@cluster0.bxjcbpr.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=notepaddb
spring.data.mongodb.auto-index-creation=true